---
title: "A three-mutants sampling example"
output: rmarkdown::html_vignette
description: >
  Sampling a three-mutants simulation
vignette: >
  %\VignetteIndexEntry{A three-mutants sampling example}
  %\VignetteEncoding{UTF-8}
  %\VignetteEngine{knitr::rmarkdown}
editor_options:
  markdown:
    wrap: 72
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

We build a tumour with three populations branching.

```{r, fig.height=4, fig.width=3}
library(rRACES)
library(dplyr)
library(ggplot2)

sim <- new(Simulation, "Three Populations")

sim$death_activation_level <- 20

sim$update_tissue(250, 250)

sim$add_mutant(name = "A", growth_rates = 0.08, death_rates = 0.01)
sim$place_cell("A", 125, 125)
sim$run_up_to_size("A", 3000)

plot_tissue(sim)
```

We sample

```{r,  fig.height=4, fig.width=3}
n_w <- n_h <- 7
ncells <- 0.8 * n_w * n_h

# Sampling ncells with random box sampling of boxes of size n_w x n_h
bbox <- sim$search_sample(c("A" = ncells), n_w, n_h)
sim$sample_cells("S_1_1", bbox$lower_corner, bbox$upper_corner)

bbox <- sim$search_sample(c("A" = ncells), n_w, n_h)
sim$sample_cells("S_1_2", bbox$lower_corner, bbox$upper_corner)

plot_tissue(sim)
```

```{r,  fig.height=4, fig.width=3, eval=FALSE}
plot_muller(sim)
```

Second mutant starts.

```{r,  fig.height=4, fig.width=3}
# New submutant
sim$add_mutant(name = "B", growth_rates = 0.13, death_rates = 0.01)
sim$mutate_progeny(sim$choose_cell_in("A"), "B")
sim$run_up_to_size("B", 400)

plot_tissue(sim)
plot_muller(sim)
```

Random sampling of cells from both mutant `A` and `B`.

```{r,  fig.height=4, fig.width=3}
# Sampling with random box sampling
bbox <- sim$search_sample(c("A" = ncells), n_w, n_h)
sim$sample_cells("S_2_1", bbox$lower_corner, bbox$upper_corner)

bbox <- sim$search_sample(c("B" = ncells), n_w, n_h)
sim$sample_cells("S_2_2", bbox$lower_corner, bbox$upper_corner)

plot_tissue(sim)
```

Finally, a third mutant branching from `A`.

```{r,  fig.height=4, fig.width=3}
# New submutant
sim$add_mutant(name = "C", growth_rates = 0.6, death_rates = 0.01)
sim$mutate_progeny(sim$choose_cell_in("A"), "C")

sim$run_up_to_size("C", 1000)
plot_tissue(sim)
plot_muller(sim)
```

With sampling of mutants `B` and `C`.

```{r,  fig.height=4, fig.width=3}
# Sampling with random box sampling
bbox <- sim$search_sample(c("B" = ncells), n_w, n_h)
sim$sample_cells("S_3_1", bbox$lower_corner, bbox$upper_corner)

bbox <- sim$search_sample(c("C" = ncells), n_w, n_h)
sim$sample_cells("S_3_2", bbox$lower_corner, bbox$upper_corner)

plot_tissue(sim, num_of_bins = 100)
plot_muller(sim)
```

Finally, the tree plot where we annotate samples and MRCAs of each
sample.

```{r,  fig.height=12, fig.width=17}
# Tree data
forest <- sim$get_samples_forest()

plot_forest(forest) %>%
  annotate_forest(forest)
```
