# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @name Simulation
#' @title Simulates the cell evolution on a tissue
#' @description The objects of this class can simulate the evolution
#'   of many cells belonging to different *species* on a tissue. Each 
#'   cell can duplicate or die according to the rates that delineate 
#'   the cell species.  
#'
#'   `Simulation` supports epigenetic evolutions, and it lets users
#'   define species pairs that have the same genotype (even though, 
#'   its genomic characterization is unknown) and differ because
#'   of their epigenetic state (i.e., either "+" or "-"). 
#'
#'   `Simulation` models epigenetic mutations and allows a cell in
#'   one of a genotype species to generate a new cell belonging to
#'   the other species of the same genotype at a specified rate.
#'
#'   `Simulation` also allows users to schedule mutations from one 
#'   genotype to a different genotype.
#' @field add_genotype Adds a genotype and its species \itemize{
#' \item \emph{Parameter:} \code{genotype} - The genotype name.
#' \item \emph{Parameter:} \code{epigenetic_rates} - The epigenetic rates of the genotype species (optional).
#' \item \emph{Parameter:} \code{growth_rates} - The duplication rates of the genotype species.
#' \item \emph{Parameter:} \code{death_rates} - The death rates of the genotype species.
#' }
#' @field choose_cell_in Chooses one cell in a genotype \itemize{
#' \item \emph{Parameter:} \code{genotype} - The genotype of the cell to choose.
#' \item \emph{Parameter:} \code{lower_corner} - The lower left corner of a rectangular selection (optional).
#' \item \emph{Parameter:} \code{upper_corner} - The upper right corner of a rectangular selection (optional).
#' \item \emph{Returns:} A list reporting "cell_id", "genotype", "epistate", "position_x",
#'    and "position_y" of the choosen cell.
#' }
#' @field death_activation_level The number of cells that activates cell death in a species
#' @field get_added_cells Gets the cells manually added to the simulation \itemize{
#' \item \emph{Returns:} A data frame reporting "genotype", "epistate", "position_x",
#'         "position_y", and "time" for each cells manually added to 
#'         the simulation.
#' }
#' @field get_cell Gets one the tissue cells \itemize{
#' \item \emph{Parameter:} \code{x} - The position of the aimed cell on the x axis.
#' \item \emph{Parameter:} \code{y} - The position of the aimed cell on the y axis.
#' \item \emph{Returns:} A data frame reporting "cell_id", "genotype", "epistate", "position_x",
#'    and "position_y" of the aimed cell.
#' }
#' @field get_cells Gets the tissue cells \itemize{
#' \item \emph{Parameter:} \code{lower_corner} - The lower-left corner of the selection frame (optional).
#' \item \emph{Parameter:} \code{upper_corner} - The upper-right corner of the selection frame (optional).
#' \item \emph{Parameter:} \code{genotype_filter} - The vector of the to-be-selected genotype names (optional).
#' \item \emph{Parameter:} \code{epigenetic_filter} - The vector of the to-be-selected epigenetic states (optional).
#' \item \emph{Returns:} A data frame reporting "cell_id", "genotype", "epistate", "position_x",
#'    and "position_y" for each cells satisfying the provided filters and laying 
#'    in the input frame.
#' }
#' @field get_clock Gets the simulated time \itemize{
#' \item \emph{Returns:} The time simulated by the simulation.
#' }
#' @field get_count_history Gets the history of the number of cells per species \itemize{
#' \item \emph{Returns:} A data frame reporting "genotype", "epistate", "counts",
#'     and "time" for each species and for each sampled time.
#' }
#' @field get_counts Counts the number of cells \itemize{
#' \item \emph{Returns:} A data frame reporting "genotype", "epistate", "counts" for each
#'      species in the simulation.
#' }
#' @field get_firing_history Gets the history of the number of fired events \itemize{
#' \item \emph{Returns:} A data frame reporting "event", "genotype", "epistate", "fired", 
#'      and "time" for each event type, for each species, and for each sampled time.
#' }
#' @field get_firings Gets the number of fired events \itemize{
#' \item \emph{Returns:} A data frame reporting "event", "genotype", "epistate", and "fired"
#'     for each event type and for each species.
#' }
#' @field get_name Gets the simulation name \itemize{
#' \item \emph{Returns:} The simulation name, which corresponds to the name of the directory 
#'         in which the simulation is saving its progresses.
#' }
#' @field get_lineage_graph Gets the simulation lineage graph\itemize{
#' \item \emph{Returns:} A data frame reporting "ancestor", "progeny", and "first_occurrence" 
#'         of each species-to-species transition.
#' }
#' @field get_rates Gets the rates of a species\itemize{
#' \item \emph{Parameter:} \code{species} - The species whose rates are aimed.
#' \item \emph{Returns:} The list of the species names.
#' }
#' @field get_samples_forest Get the samples forest\itemize{
#' \item \emph{Returns:} The descendants forest having as leaves the sampled cells.
#' }
#' @field get_samples_info Retrieve information about the samples \itemize{
#' \item \emph{Returns:} A data frame containing, for each sample collected 
#'         during the simulation, the columns "name", "time", "ymin", 
#'         "xmin", "ymax", "xmax", and  "tumoral cells". "ymin", 
#'         "xmin", "ymax", "xmax" report the boundaries of the sampled 
#'         rectangular region, while "tumoral cells" is the number of 
#'         tumoral cells in the sample.
#' }
#' @field get_species Gets the species \itemize{
#' \item \emph{Returns:} A data frame describing the registered species.
#' }
#' @field get_tissue_name Gets the tissue name \itemize{
#' \item \emph{Returns:} The name of the simulated tissue.
#' }
#' @field get_tissue_size Gets the size of the simulated tissue \itemize{
#' \item \emph{Returns:} The vector `c(x_size, y_size)` of the simulated tissue.
#' }
#' @field mutate_progeny Generate a mutated offspring \itemize{
#' \item \emph{Parameter:} \code{cell_position} - The position of the cell whose offspring will mutate.
#' \item \emph{Parameter:} \code{mutated_genotype} - The genotype of the mutated cell.
#' }
#' or
#' \itemize{
#' \item \emph{Parameter:} \code{x} - The position of the cell whose progeny will mutate on the x axis.
#' \item \emph{Parameter:} \code{y} - The position of the cell whose progeny will mutate on the y axis.
#' \item \emph{Parameter:} \code{mutated_genotype} - The genotype of the mutated cell.
#' }
#' @field place_cell Place one cell in the tissue \itemize{
#' \item \emph{Parameter:} \code{species} - The name of the new cell species.
#' \item \emph{Parameter:} \code{x} - The position on the x axis of the cell.
#' \item \emph{Parameter:} \code{y} - The position on the y axis of the cell.
#' }
#' @field schedule_genotype_mutation Schedules a genotype mutation \itemize{
#' \item \emph{Parameter:} \code{src} - The name of the genotype from which the mutation occurs.
#' \item \emph{Parameter:} \code{dest} - The name of the genotype to which the mutation leads.
#' \item \emph{Parameter:} \code{time} - The simulated time at which the mutation will occurs.
#' }
#' @field run_up_to_event Simulates cell evolution \itemize{
#' \item \emph{Parameter:} \code{event} - The considered event type, i.e., "growth", "death", or "switch".
#' \item \emph{Parameter:} \code{species} - The species whose event number is considered.
#' \item \emph{Parameter:} \code{num_of_events} - The threshold for the event number.
#' }
#' @field run_up_to_size Simulates cell evolution \itemize{
#' \item \emph{Parameter:} \code{species} - The species whose number of cells is considered.
#' \item \emph{Parameter:} \code{num_of_cells} - The threshold for the cell number.
#' }
#' @field run_up_to_time Simulates cell evolution \itemize{
#' \item \emph{Parameter:} \code{time} - The final simulation time.
#' }
#' @field sample_cells Sample a tissue rectangle region \itemize{
#' \item \emph{Parameter:} \code{name} - The sample name.
#' \item \emph{Parameter:} \code{lower_corner} - The bottom-left corner of the rectangle.
#' \item \emph{Parameter:} \code{upper_corner} - The top-right corner of the rectangle.
#' }
#' @field update_rates Updates the rates of a species\itemize{
#' \item \emph{Parameter:} \code{species} - The species whose rates must be updated.
#' \item \emph{Parameter:} \code{rates} - The list of the rates to be updated.
#' \item \emph{Returns:} The vector of the species names.
#' }
#' @field update_tissue Updates tissue name and size \itemize{
#' \item \emph{Parameter:} \code{name} - The new name of the tissue (optional).
#' \item \emph{Parameter:} \code{width} - The width of the new tissue.
#' \item \emph{Parameter:} \code{height} - The height of the new tissue.
#' }
NULL

#' @name Simulation$new
#' @title Constructs a new Simulation
#' @param output_dir The output directory (optional).
#' @param seed The seed for the pseudo-random generator (optional).
#' @examples
#' sim <- new(Simulation)
#' sim <- new(Simulation, "test")
#' sim <- new(Simulation, "test", 13)
NULL

#' @name Simulation$update_tissue 
#' @title Update tissue name and size
#' @param name The new name of the tissue (optional).
#' @param width The width of the new tissue.
#' @param height The height of the new tissue.
#' @examples
#' sim <- new(Simulation, "update_tissue_test")
#'
#' # set the tissue size, but not the name
#' sim$update_tissue(1200, 900)
#'
#' # set the tissue size and its name
#' sim$update_tissue("Liver", 1200, 900)
NULL

#' @name Simulation$add_genotype 
#' @title Adds a genotype and its species
#' @description This method adds a genotype and its species to the
#'      simulation. If the optional parameter `epigenetic_rate` is 
#'      provided, then two new species having the same genotype and 
#'      opposite epigenetic states are created. When, instead, the
#'      optional parameter `epigenetic_rate` is missing, this
#'      method creates only one species with no epigenetic states.
#' @param genotype The genotype name.
#' @param epigenetic_rates The epigenetic rates of the genotype species (optional).
#' @param growth_rates The duplication rates of the genotype species.
#' @param death_rates The death rates of the genotype species.
#' @examples
#' sim <- new(Simulation, "add_genotype_test")
#'
#' # create the two species "A+" and "A-". They both have genotype "A".
#' sim$add_genotype(genotype = "A",
#'                  epigenetic_rates = c("+-" = 0.01, "-+" = 0.01),
#'                  growth_rates = c("+" = 0.2, "-" = 0.08),
#'                  death_rates = c("+" = 0.1, "-" = 0.01))
#'
#' # create the species "C" its genotype is "C".
#' sim$add_genotype(genotype = "C", growth_rate = 0.2, death_rate = 0.1)
NULL

#' @name Simulation$get_species
#' @title Gets the species
#' @return A data frame reporting "genotype", "epistate", "growth_rate", 
#'    "death_rate", and "switch_rate" for each registered species.
#' @examples
#' sim <- new(Simulation, "get_species_test")
#' sim$add_genotype("A", growth_rate = 0.2, death_rate = 0.1)
#' sim$add_genotype("B", growth_rate = 0.15, death_rate = 0.05)
#'
#' # get the added species and their rates. In this case, "A" 
#' # and "B"
#' sim$get_species()
NULL

#' @name Simulation$place_cell 
#' @title Place one cell in the tissue 
#' @param species The name of the new cell species.
#' @param x The position on the x axis of the cell.
#' @param y The position on the y axis of the cell.
#' @examples
#' sim <- new(Simulation, "place_cell_test")
#' sim$add_genotype(genotype = "A",
#'                  epigenetic_rates = c("+-" = 0.01, "-+" = 0.01),
#'                  growth_rates = c("+" = 0.2, "-" = 0.08),
#'                  death_rates = c("+" = 0.1, "-" = 0.01))
#'
#' # add into the tissue a cell of species "A+" in position (500,500)
#' sim$place_cell("A+", 500, 500)
NULL

#' @name Simulation$get_cell
#' @title Gets one of the tissue cells
#' @description This method collects some data of the aimed cell without altering 
#'      the tissue.
#' @param x The position of the aimed cell on the x axis.
#' @param y The position of the aimed cell on the y axis.
#' @return A data frame reporting "cell_id", "genotype", "epistate", "position_x", 
#'    and "position_y" of the aimed cell.
#' @examples
#' sim <- new(Simulation, "get_cell_test")
#' sim$add_genotype(genotype = "A",
#'                  epigenetic_rates = c("+-" = 0.01, "-+" = 0.01),
#'                  growth_rates = c("+" = 0.2, "-" = 0.08),
#'                  death_rates = c("+" = 0.1, "-" = 0.01))
#' sim$add_genotype(genotype = "B",
#'                  epigenetic_rates = c("+-" = 0.02, "-+" = 0.01),
#'                  growth_rates = c("+" = 0.3, "-" = 0.1),
#'                  death_rates = c("+" = 0.1, "-" = 0.01))
#' sim$schedule_genotype_mutation(src = "A", dst = "B", time = 50)
#' sim$place_cell("A+", 500, 500)
#' sim$run_up_to_time(70)
#' 
#' # collect all the cells in the tissue
#' sim$get_cell(501, 502)
NULL

#' @name Simulation$get_cells
#' @title Gets the tissue cells
#' @description This method collects some data about the cells in the tissue
#'      without altering the tissue itself. The pairs of optional parameters
#'      `lower_corner` and `upper_corner` define a frame of the tissue in
#'      which the data are sampled. The optional parameters `genotype_filter`
#'      and `epigenetic_filter` filter the collected cell data according to
#'      the cell genotype and epigenetic state.
#' @param lower_corner The lower-left corner of the selection frame (optional).
#' @param upper_corner The upper-right corner of the selection frame (optional).
#' @param genotype_filter The vector of the to-be-selected genotype names (optional).
#' @param epigenetic_filter The vector of the to-be-selected epigenetic states (optional).
#' @return A data frame reporting "cell_id", "genotype", "epistate", "position_x", 
#'    and "position_y" for each cells satisfying the provided filters and laying 
#'    in the input frame.
#' @examples
#' sim <- new(Simulation, "get_cells_test")
#' sim$add_genotype(genotype = "A",
#'                  epigenetic_rates = c("+-" = 0.01, "-+" = 0.01),
#'                  growth_rates = c("+" = 0.2, "-" = 0.08),
#'                  death_rates = c("+" = 0.1, "-" = 0.01))
#' sim$add_genotype(genotype = "B",
#'                  epigenetic_rates = c("+-" = 0.02, "-+" = 0.01),
#'                  growth_rates = c("+" = 0.3, "-" = 0.1),
#'                  death_rates = c("+" = 0.1, "-" = 0.01))
#' sim$schedule_genotype_mutation(src = "A", dst = "B", time = 50)
#' sim$place_cell("A+", 500, 500)
#' sim$run_up_to_time(70)
#' 
#' # collect all the cells in the tissue
#' sim$get_cells()
#'
#' # get the cells in the frame [495,505]x[490,500]
#' sim$get_cells(lower_corner=c(495,490), upper_corner=c(505,500))
#'
#' # cells can be filtered by genotype name...
#' sim$get_cells(genotype_filter=c("A"),epigenetic_filter=c("+","-"))
#'
#' # ...or by epigenetic state
#' sim$get_cells(genotype_filter=c("A","B"),epigenetic_filter=c("-"))
#'
#' # cells can be filtered by frame, genotype, and epigenetic states
#' sim$get_cells(lower_corner=c(495,495), upper_corner=c(505,505),
#'               genotype_filter=c("A"),epigenetic_filter=c("+","-"))
NULL

#' @name Simulation$get_counts
#' @title Counts the number of cells
#' @return A data frame reporting "genotype", "epistate", "counts" for each 
#'      species in the simulation.
#' @examples
#' sim <- new(Simulation, "get_counts_test")
#' sim$add_genotype("A", growth_rate = 0.2, death_rate = 0.1)
#' sim$add_genotype("B", growth_rate = 0.15, death_rate = 0.05)
#' sim$schedule_genotype_mutation(src = "A", dst = "B", time = 50)
#' sim$place_cell("A", 500, 500)
#' sim$run_up_to_time(70)
#'
#' # counts the number of cells per species
#' sim$get_counts()
NULL

#' @name Simulation$get_added_cells
#' @title Gets the cells manually added to the simulation
#' @return A data frame reporting "genotype", "epistate", "position_x",
#'         "position_y", and "time" for each cells manually added to 
#'         the simulation.
#' @examples
#' sim <- new(Simulation, "get_added_cells")
#' sim$add_genotype(genotype = "A",
#'                  epigenetic_rates = c("+-" = 0.01, "-+" = 0.01),
#'                  growth_rates = c("+" = 0.2, "-" = 0.08),
#'                  death_rates = c("+" = 0.1, "-" = 0.01))
#' sim$add_genotype(genotype = "B",
#'                  epigenetic_rates = c("+-" = 0.02, "-+" = 0.01),
#'                  growth_rates = c("+" = 0.3, "-" = 0.1),
#'                  death_rates = c("+" = 0.1, "-" = 0.01))
#' sim$schedule_genotype_mutation(src = "A", dst = "B", time = 30)
#' sim$place_cell("A+", 500, 500)
#' sim$run_up_to_time(50)
#'
#' # counts the number of cells per species
#' sim$get_added_cells()
NULL

#' @name Simulation$schedule_genotype_mutation
#' @title Schedules a genotype mutation
#' @description This method schedules a genotype mutation that can occur 
#'      from any of the species of the source genotype to the species of 
#'      the destination genotype with a consistent epigenetic state. 
#'      For the sake of example, if the mutation from "A" to "B" is 
#'      scheduled, then we have three possible situations:
#'      1. The genotype "A" consists of the only species "A". Then,
#'         during one duplication of a cell of "A", one cell of "B"
#'         will arise.
#'      2. The genotype "A" consists of the species "A+" and "A-" and
#'         during one duplication of a cell of "A+", one cell of "B+" 
#'         will arise.
#'      3. The genotype "A" consists of the species "A+" and "A-" and
#'         during one duplication of a cell of "A-", one cell of "B-"
#'         will arise.
#'      No other scenario can occur.
#' @param src The name of the genotype from which the mutation occurs.
#' @param dest The name of the genotype to which the mutation leads.
#' @param time The simulated time at which the mutation will occurs.
#' @examples
#' sim <- new(Simulation, "schedule_genotype_mutation_test")
#' sim$add_genotype(genotype = "A",
#'                  epigenetic_rates = c("+-" = 0.01, "-+" = 0.01),
#'                  growth_rates = c("+" = 0.2, "-" = 0.08),
#'                  death_rates = c("+" = 0.1, "-" = 0.01))
#' sim$add_genotype(genotype = "B",
#'                  epigenetic_rates = c("+-" = 0.02, "-+" = 0.01),
#'                  growth_rates = c("+" = 0.3, "-" = 0.1),
#'                  death_rates = c("+" = 0.1, "-" = 0.01))
#'
#' # schedule an evolution from genotype "A" to genotype "B" at time 50
#' sim$schedule_genotype_mutation(src = "A", dst = "B", time = 50)
NULL

#' @name Simulation$get_lineage_graph
#' @title Gets the simulation lineage graph
#' @description At the beginning of the computation only the species of the added
#'         cells are present in the tissue. As the simulation proceeds new species 
#'         arise as a consequence of either genotype mutations or epigenetic 
#'         switches. The *lineage graph* stores these species evolutions and it 
#'         reports the first occurrence time of any species-to-species transition.
#'
#'         This method returns the lineage graph of the simulation.
#' @return A data frame reporting "ancestor", "progeny", and "first_occurrence" of
#'         each species-to-species transition.
#' @examples
#' sim <- new(Simulation, "get_lineage_graph_test")
#' sim$add_genotype(genotype = "A",
#'                  epigenetic_rates = c("+-" = 0.01, "-+" = 0.01),
#'                  growth_rates = c("+" = 0.2, "-" = 0.08),
#'                  death_rates = c("+" = 0.1, "-" = 0.01))
#' sim$add_genotype(genotype = "B",
#'                  epigenetic_rates = c("+-" = 0.02, "-+" = 0.01),
#'                  growth_rates = c("+" = 0.3, "-" = 0.1),
#'                  death_rates = c("+" = 0.1, "-" = 0.01))
#' sim$schedule_genotype_mutation(src = "A", dst = "B", time = 20)
#' sim$run_up_to_time(50)
#'
#' sim$get_lineage_graph()
NULL

#' @name Simulation$run_up_to_time
#' @title Simulates cell evolution
#' @param time The final simulation time.
#' @examples
#' sim <- new(Simulation, "run_up_to_time_test")
#' sim$add_genotype("A", growth_rate = 0.2, death_rate = 0.1)
#' sim$place_cell("A", 500, 500)
#'
#' # simulate the tissue up to simulate timed 100
#' sim$run_up_to_time(100)
NULL

#' @name Simulation$run_up_to_size
#' @title Simulates cell evolution 
#' @description This method simulates cell evolution until the number of cells in 
#'       a species reaches a specified threshold.
#' @param species The species whose number of cells is considered.
#' @param num_of_cells The threshold for the cell number.
#' @examples
#' sim <- new(Simulation, "run_up_to_size_test")
#' sim$add_genotype(genotype = "A",
#'                  epigenetic_rates = c("+-" = 0.01, "-+" = 0.01),
#'                  growth_rates = c("+" = 0.2, "-" = 0.08),
#'                  death_rates = c("+" = 0.1, "-" = 0.01))
#' sim$place_cell("A+", 500, 500)
#'
#' # simulate the tissue until the species "A+" account for 100 
#' # contemporary cells
#' sim$run_up_to_size(species = "A+", num_of_cells = 100)
NULL

#' @name Simulation$run_up_to_event
#' @title Simulates cell evolution
#' @description This method simulates cell evolution until the number of events that 
#'         have occurred to cells of a species reaches a specified threshold.
#' @param event The considered event, i.e., "growth", "death", or "switch".
#' @param species The species whose event number is considered.
#' @param num_of_events The threshold for the event number.
#' @examples
#' sim <- new(Simulation, "run_up_to_event_test")
#' sim$add_genotype(genotype = "A",
#'                  epigenetic_rates = c("+-" = 0.01, "-+" = 0.01),
#'                  growth_rates = c("+" = 0.2, "-" = 0.08),
#'                  death_rates = c("+" = 0.1, "-" = 0.01))
#' sim$place_cell("A+", 500, 500)
#'
#' # simulate the cell evolution until the number of epigenetic events from 
#' # the species "A+" is less than 100.
#' sim$run_up_to_event(event = "switch", species = "A+", num_of_events = 100)
NULL

#' @name Simulation$get_clock 
#' @title Gets the simulated time
#' @return The time simulated by the simulation.
#' @examples
#' sim <- new(Simulation, "get_clock_test")
#' sim$add_genotype(genotype = "A",
#'                  epigenetic_rates = c("+-" = 0.01, "-+" = 0.01),
#'                  growth_rates = c("+" = 0.2, "-" = 0.08),
#'                  death_rates = c("+" = 0.1, "-" = 0.01))
#' sim$place_cell("A+", 500, 500)
#' sim$run_up_to_event("switch", "A+", 100)
#'
#' # get the simulated time
#' sim$get_clock()
NULL

#' @name Simulation$get_firings 
#' @title Gets the number of fired events 
#' @return A data frame reporting "event", "genotype", "epistate", and "fired"
#'     for each event type, genotype, and epigenetic states.
#' @examples
#' sim <- new(Simulation, "get_firings_test")
#' sim$add_genotype(genotype = "A",
#'                  epigenetic_rates = c("+-" = 0.01, "-+" = 0.01),
#'                  growth_rates = c("+" = 0.2, "-" = 0.08),
#'                  death_rates = c("+" = 0.1, "-" = 0.01))
#' sim$place_cell("A+", 500, 500)
#' sim$run_up_to_event("switch", "A+", 100)
#'
#' # get the number of event fired per event and species
#' sim$get_firings()
NULL

#' @name Simulation$get_firing_history 
#' @title Gets the history of the number of fired events 
#' @description This method returns a data frame reporting the number of 
#'           events fired up to each sampled simulation time.
#' @return A data frame reporting "event", "genotype", "epistate", "fired",
#'     and "time" for each event type, for each species, and for each 
#'     sampled time.
#' @examples
#' sim <- new(Simulation, "get_firing_history_test")
#' sim$add_genotype(genotype = "A",
#'                  epigenetic_rates = c("+-" = 0.01, "-+" = 0.01),
#'                  growth_rates = c("+" = 0.2, "-" = 0.08),
#'                  death_rates = c("+" = 0.1, "-" = 0.01))
#' sim$place_cell("A+", 500, 500)
#' sim$history_delta <- 20 
#' sim$run_up_to_time(70)
#'
#' # get the number of event fired per event and species
#' sim$get_firing_history()
NULL

#' @name Simulation$get_count_history
#' @title Gets the history of the number of cells per species
#' @description This method returns a data frame reporting the number of 
#'           species cells in each sampled simulation time.
#' @return A data frame reporting "genotype", "epistate", "counts",
#'     and "time" for each species, and for each sampled time.
#' @examples
#' sim <- new(Simulation, "get_count_history")
#' sim$add_genotype("A", growth_rate = 0.2, death_rate = 0.1)
#' sim$add_genotype("B", growth_rate = 0.15, death_rate = 0.05)
#' sim$schedule_genotype_mutation(src = "A", dst = "B", time = 50)
#' sim$place_cell("A", 500, 500)
#' sim$history_delta <- 20 
#' sim$run_up_to_time(70)
#' 
#' # get the history of species counts
#' sim$get_count_history()
NULL

#' @name Simulation$get_name 
#' @title Gets the simulation name
#' @return The simulation name, which corresponds to the name of the directory 
#'         in which the simulation is saving its progresses.
#' @examples
#' sim <- new(Simulation, "test")
#'
#' # Expecting "test"
#' sim$get_name()
NULL

#' @name Simulation$get_tissue_name 
#' @title Gets the tissue name
#' @return The name of the simulated tissue.
#' @examples
#' sim <- new(Simulation, "test")
#' sim$update_tissue("Liver", 1200, 900)
#'
#' # get the tissue name, i.e., expecting "Liver"
#' sim$get_tissue_name()
NULL

#' @name Simulation$get_tissue_size 
#' @title Gets the size of the simulated tissue
#' @return The vector `c(x_size, y_size)` of the simulated tissue.
#' @examples
#' sim <- new(Simulation, "get_tissue_size_test")
#' sim$update_tissue("Liver", 1200, 900)
#'
#' # get the tissue size, i.e., expecting c(1200,900)
#' sim$get_tissue_size()
NULL

#' @name Simulation$get_rates
#' @title Get the rates of a species
#' @param species The species whose rates are aimed.
#' @return The list of the species rates.
#' @examples
#' sim <- new(Simulation, "get_rates_test")
#' sim$add_genotype(genotype = "A",
#'                  epigenetic_rates = c("+-" = 0.01, "-+" = 0.02),
#'                  growth_rates = c("+" = 0.2, "-" = 0.08),
#'                  death_rates = c("+" = 0.1, "-" = 0.01))
#'
#' # Get the rates of "A-". In this case c("growth"=0.08, "death"=0.01, "switch"=0.02) is expected
#' sim$get_rates("A-")
NULL

#' @name Simulation$update_rates
#' @title Update the rates of a species
#' @param species The species whose rates must be updated.
#' @param rates The list of rates to be updated.
#' @examples
#' sim <- new(Simulation, "update_rates_test")
#' sim$add_genotype(genotype = "A",
#'                  epigenetic_rates = c("+-" = 0.01, "-+" = 0.01),
#'                  growth_rates = c("+" = 0.2, "-" = 0.08),
#'                  death_rates = c("+" = 0.1, "-" = 0.01))
#'
#' # Set the death and epigenetic switch rates of "A-" to 0
#' sim$update_rates("A-", c(switch=0, death=0))
NULL

#' @name Simulation$choose_cell_in
#' @title Chooses one cell in a genotype
#' @description This method chooses one of the cells whose genotype
#'         is `genotype`. Optionally, the lower and upper corners 
#'         of a tissue rectangular selection can be provided
#'         to obtain one cell in the rectangle.
#' @param genotype The genotype of the cell to choose.
#' @param lower_corner The lower corner of the rectangular selection (optional).
#' @param upper_corner The upper corner of the rectangular selection (optional).
#' @return A list reporting "cell_id", "genotype", "epistate", "position_x",
#'    and "position_y" of the choosen cell.
#' @examples
#' sim <- new(Simulation, "choose_cell_in_test")
#' sim$add_genotype(genotype = "A",
#'                  epigenetic_rates = c("+-" = 0.01, "-+" = 0.01),
#'                  growth_rates = c("+" = 0.2, "-" = 0.08),
#'                  death_rates = c("+" = 0.1, "-" = 0.01))
#' sim$add_genotype(genotype = "B",
#'                  epigenetic_rates = c("+-" = 0.1, "-+" = 0.01),
#'                  growth_rates = c("+" = 0.15, "-" = 0.3),
#'                  death_rates = c("+" = 0.1, "-" = 0.01))
#' sim$place_cell("A+", 500, 500)
#' sim$death_activation_level <- 100
#' sim$schedule_genotype_mutation("A","B",20)
#' sim$run_up_to_size(species = "B-", num_of_cells = 50)
#'
#' # Randomly choose one cell in "B" in the tissue
#' sim$choose_cell_in(genotype = "B")
NULL

#' @name Simulation$mutate_progeny
#' @title Generate a mutated progeny
#' @description This method simulates both the duplication of the cell in the 
#'       specified position and the birth of one cells of a given 
#'       genotype that preserves the epigenetic status of the original cell.
#'       The mutated cell will be located in the position of its parent.
#' @param cell_position The position of the cell whose offspring will mutate.
#' @param mutated_genotype The genotype of the mutated cell.
#' @examples
#' sim <- new(Simulation, "mutate_progeny_test")
#' sim$add_genotype(genotype = "A",
#'                  epigenetic_rates = c("+-" = 0.01, "-+" = 0.01),
#'                  growth_rates = c("+" = 0.2, "-" = 0.08),
#'                  death_rates = c("+" = 0.1, "-" = 0.01))
#' sim$place_cell("A+", 500, 500)
#' sim$run_up_to_time(70)
#'
#' sim$add_genotype(genotype = "B",
#'                  epigenetic_rates = c("+-" = 0.1, "-+" = 0.01),
#'                  growth_rates = c("+" = 0.15, "-" = 0.3),
#'                  death_rates = c("+" = 0.1, "-" = 0.01))
#'
#' # duplicate the cell in position (503, 492). One of 
#' # its direct descendents will have genotype "B"
#' sim$mutate_progeny(503, 492, "B")
#'
#' # the output of `choose_cell_in` and `get_cell` can also be used
#' # as input for `mutate_progeny`
#' sim$mutate_progeny(sim$choose_cell_in("A"), "B")
NULL

#' @name Simulation$sample_cells
#' @title Sample a tissue rectangle region.
#' @description This method removes a rectangular region from the simulated
#'       tissue and stores its cells in a sample that can subsequently 
NULL

#' @examples
#' sim <- new(Simulation, "sample_cells_test")
#' sim$add_genotype(genotype = "A",
#'                  growth_rate = 0.2,
#'                  death_rate = 0.01)
#' sim$place_cell("A", 500, 500)
#'
#' sim$death_activation_level <- 100
#' sim$run_up_to_size(species = "A", num_of_cells = 50000)
#'
#' # sample the region [450,500]x[475,550]
#' sim$sample_cells("S1", lower_corner=c(450,475), upper_corner=c(500,550))
NULL

#' @name Simulation$get_samples_info
#' @title Retrieve information about the samples
#' @description This method retrieves information about 
#'           the samples collected along the simulation.
#'           It returns a data frame reporting, for each
#'           sample, the name, the sampling time, the 
#'           position, and the number of tumoural cells. 
#' @examples
#' sim <- new(Simulation, "get_samples_info_test")
#' sim$add_genotype(genotype = "A",
#'                  growth_rate = 0.2,
#'                  death_rate = 0.01)
#' sim$place_cell("A", 500, 500)
#'
#' sim$death_activation_level <- 100
#' sim$run_up_to_size(species = "A", num_of_cells = 50000)
#'
#' # sample the region [450,500]x[475,550]
#' sim$sample_cells("S1", lower_corner=c(450,475),
#'                  upper_corner=c(500,550))
#'
#' # simulate 1 time unit more
#' sim$run_up_to_time(sim$get_clock()+1)
#'
#' # sample the region [500,520]x[525,550]
#' sim$sample_cells("S2", lower_corner=c(500,525),
#'                  upper_corner=c(520,550))
#'
#' # get information about all the collected 
#' # samples, i.e, S1 and S2
#' sim$get_samples_info()
NULL

#' @name Simulation$death_activation_level
#' @title The number of cells that activates cell death in a species.
#' @description This value is the minimum number of cells that
#'       enables cell death in a species. The cell of a species $S$ can die
#'       if and only if that $S$ has reached the death activation level at
#'       least once during the simulation.
#' @examples
#' sim <- new(Simulation, "death_activation_level_test")
#'
#' # get the simulation death activation level
#' sim$death_activation_level
#'
#' # set the death activation level to 50
#' sim$death_activation_level <- 50
NULL

#' @name Simulation$history_delta
#' @title The delta time between time series samples
#' @description This value is the maximum time between two successive 
#'          time series data samples. 
#' @examples
#' sim <- new(Simulation, "death_activation_level_test")
#'
#' # get the delta time between two time series samples (0 by default)
#' sim$history_delta
#'
#' # set the delta time between two time series samples
#' sim$death_activation_level <- 20
NULL

#' @name recover_simulation
#' @title Load a simulation
#' @param name The name of the simulation to be recovered
#' @examples
#' # create a simulation having name "recover_simulation_test"
#' sim <- new(Simulation, "recover_simulation_test")
#'
#' # add the species of "A"
#' sim$add_genotype("A",
#'                  epigenetic_rates=c("+-" = 0.01, "-+"=0.01),
#'                  growth_rates = c("+"=0.1, "-"=0.01),
#'                  death_rates = c("+"=0.05, "-"=0.005))
#'
#' # place a cell in the tissue
#' sim$place_cell("A+", 500, 500)
#'
#' # simulate up to time 50
#' sim$run_up_to_time(50)
#'
#' # show the simulation
#' sim
#'
#' # remove the object sim from the environment
#' rm(list=c("sim"))
#'
#' # the object pointed by sim does not exist any more
#' exists("sim")
#' 
#' # recover the simulation from the directory "recover_simulation_test"
#' sim <- recover_simulation("recover_simulation_test")
#'
#' sim
NULL

#' @name SamplesForest
#' @title The forest of the sampled cell ancestors.
#' @description Represents the forest of the ancestors of the 
#'       cells sampled during the computation. The leaves of 
#'       this forest are the sampled cells.
#' @field get_coalescent_cells Retrieve most recent common ancestors\itemize{
#' \item \emph{Parameter:} \code{cell_ids} - The list of the identifiers of the 
#'               cells whose most recent common ancestors are aimed (optional).
#' \item \emph{Return:} A data frame representing, for each of the identified 
#'         cells, the identified (column "cell_id"), whenever the
#'         node is not a root, the ancestor identifier (column 
#'         "ancestor"), whenever the node was sampled, i.e., it is
#'         one of the forest leaves, the name of the sample
#'         containing the node, (column "sample"), the genotype
#'         (column "genotype"), the epistate (column "epistate"),
#'         and the birth time (column "birth_time").
#' }
#' @field get_nodes Get the forest nodes \itemize{
#' \item \emph{Return:} A data frame representing, for each node
#'              in the forest, the identified (column "id"), 
#'              whenever the node is not a root, the ancestor 
#'              identifier (column "ancestor"), whenever the node 
#'              was sampled, i.e., it is one of the forest
#'              leaves, the name of the sample containing the 
#'              node, (column "sample"), the genotype (column 
#'              "genotype"), the epistate (column "epistate"),
#'              and the birth time (column "birth_time").
#' }
#' @field get_samples_info Retrieve information about the samples \itemize{
#' \item \emph{Returns:} A data frame containing, for each sample collected 
#'         during the simulation, the columns "name", "time", "ymin", 
#'         "xmin", "ymax", "xmax", and  "tumoral cells". "ymin", 
#'         "xmin", "ymax", "xmax" report the boundaries of the sampled 
#'         rectangular region, while "tumoral cells" is the number of 
#'         tumoral cells in the sample.
#' }
#' @field get_species_info Gets the species data\itemize{
#' \item \emph{Returns:} A data frame reporting "genotype" and "epistate" 
#'            for each registered species.
#' }
#' @field get_subforest_for Build a subforest using as leaves some of the original samples \itemize{
#' \item \emph{Parameter:} \code{sample_names} - The names of the samples whose cells will be used
#'         as leaves of the new forest.
#' \item \emph{Returns:} A samples forest built on the samples mentioned in `sample_names`.
#' }
NULL

#' @name SamplesForest$get_nodes
#' @title Get the nodes of the forest
#' @return A data frame representing, for each node
#'         in the forest, the identified (column "cell_id"), 
#'         whenever the node is not a root, the ancestor 
#'         identifier (column "ancestor"), whenever the 
#'         node was sampled, i.e., it is one of the forest
#'         leaves, the name of the sample containing the 
#'         node, (column "sample"), the genotype (column 
#'         "genotype"), the epistate (column "epistate"),
#'         and the birth time (column "birth_time").
#' @examples
#' # create a simulation having name "get_nodes_test"
#' sim <- new(Simulation, "get_nodes_test")
#' sim$add_genotype(genotype = "A",
#'                  growth_rate = 0.2,
#'                  death_rate = 0.01)
#' sim$place_cell("A", 500, 500)
#'
#' sim$death_activation_level <- 100
#' sim$run_up_to_size(species = "A", num_of_cells = 50000)
#'
#' # sample the region [450,500]x[475,550]
#' sim$sample_cells("S1", lower_corner=c(450,475), upper_corner=c(500,550))
#'
#' # build the samples forest
#' forest <- sim$get_samples_forest()
#'
#' forest$get_nodes()
NULL

#' @name SamplesForest$get_samples_info
#' @title Retrieve information about the samples
#' @description This method retrieves information about 
#'           the samples whose cells were used as leaves
#'           of the samples forest.
#' @return A data frame reporting, for each sample, the 
#'           name, the sampling time, the position, and 
#'           the number of tumoural cells.
#' @examples
#' sim <- new(Simulation, "get_samples_info_2_test")
#' sim$add_genotype(genotype = "A",
#'                  growth_rate = 0.2,
#'                  death_rate = 0.01)
#' sim$place_cell("A", 500, 500)
#'
#' sim$death_activation_level <- 100
#' sim$run_up_to_size(species = "A", num_of_cells = 50000)
#'
#' # sample the region [450,500]x[475,550]
#' sim$sample_cells("S1", lower_corner=c(450,475), upper_corner=c(500,550))
#'
#' # build the samples forest
#' forest <- sim$get_samples_forest()
#'
#' # get information about the sampled whose cells  
#' # are the forest leaves, i.e, S1 and S2
#' forest$get_samples_info()
NULL

#' @name SamplesForest$get_coalescent_cells
#' @title Retrieve most recent common ancestors
#' @description This method retrieves the most recent common ancestors
#'         of a set of cells. If the optional parameter `cell_ids` is 
#'         used, this method find the most recent common ancestors of 
#'         the cells having an identifier among those in `cell_ids`.
#'         If, otherwise, the optional parameter is not used, this
#'         method find the most recent common ancestors of the forest
#'         leaves.
#' @param cell_ids The list of the identifiers of the cells whose
#'         most recent common ancestors are aimed (optional).
#' @return A data frame representing, for each of the identified 
#'         cells, the identified (column "cell_id"), whenever the
#'         node is not a root, the ancestor identifier (column 
#'         "ancestor"), whenever the node was sampled, i.e., it is
#'         one of the forest leaves, the name of the sample
#'         containing the node, (column "sample"), the genotype
#'         (column "genotype"), the epistate (column "epistate"),
#'         and the birth time (column "birth_time").
#' @examples
#' sim <- new(Simulation, "get_coalescent_cells_test")
#' sim$add_genotype(genotype = "A",
#'                  growth_rate = 0.2,
#'                  death_rate = 0.01)
#' sim$place_cell("A", 500, 500)
#'
#' sim$death_activation_level <- 100
#' sim$run_up_to_size(species = "A", num_of_cells = 50000)
#'
#' # sample the region [450,500]x[475,550]
#' sim$sample_cells("S1", lower_corner=c(450,475), upper_corner=c(500,550))
#'
#' # build the samples forest
#' forest <- sim$get_samples_forest()
#'
#' forest$get_coalescent_cells()
NULL

#' @name SamplesForest$get_subforest_for
#' @title Build a subforest using as leaves some of the original samples
#' @param sample_names The names of the samples whose cells will be used
#'         as leaves of the new forest 
#' @return A samples forest built on the samples mentioned in `sample_names` 
#' @examples
#' sim <- new(Simulation, "get_subforest_for_test")
#' sim$add_genotype(genotype = "A",
#'                  growth_rate = 0.2,
#'                  death_rate = 0.01)
#' sim$place_cell("A", 500, 500)
#'
#' sim$death_activation_level <- 100
#' sim$run_up_to_size(species = "A", num_of_cells = 50000)
#'
#' # sample the region [450,500]x[475,550]
#' sim$sample_cells("S1", lower_corner=c(450,475), upper_corner=c(500,550))
#'
#' sim$run_up_to_size(species = "A", num_of_cells = 60000)
#'
#' # sample again the same region
#' sim$sample_cells("S2", lower_corner=c(450,475), upper_corner=c(500,550))
#'
#' # build the samples forest
#' forest <- sim$get_samples_forest()
#'
#' forest$get_subforest_for("S2")
NULL

#' @name SamplesForest$get_species_info
#' @title Gets the species
#' @return A data frame reporting "genotype" and "epistate" 
#'            for each registered species.
NULL

#' @name Simulation$get_samples_forest
#' @title Get the samples forest
#' @return The samples forest having as leaves the sampled cells
#' @examples
#' sim <- new(Simulation, "get_samples_forest_test")
#' sim$add_genotype(genotype = "A",
#'                  growth_rate = 0.2,
#'                  death_rate = 0.01)
#' sim$place_cell("A", 500, 500)
#'
#' sim$death_activation_level <- 100
#' sim$run_up_to_size(species = "A", num_of_cells = 50000)
#'
#' # sample the region [450,500]x[475,550]
#' sim$sample_cells("S1", lower_corner=c(450,475), upper_corner=c(500,550))
#'
#' # build the samples forest
#' forest <- sim$get_samples_forest()
NULL

